var config = {
	schedule_link			:"http://m.cgv.vn/vn/sessiontime/",
	department_link			:"http://m.cgv.vn/vn/cinemas/",
	//onScreen_movie_link		: "http://m.cgv.vn/vn/movies/",
	onScreen_movie_link		: "https://www.cgv.vn/vn/movies/now-showing.html",
	commingSoon_movie_link 	: "http://www.cgv.vn/vn/comingsoon/",
	promotion_link 			: "http://m.cgv.vn/vn/latestoffers/",
	schedule:{
		department_container	:"ul[data-role=listview] li",
		department_name			:"a",
		movie_container			:"ul[data-role=listview] li",
		movie_name				:"a",
		time_container			:"div.ss-list > div",
		time_date				:"span:first-child",
		time_hour				:"ul > li > div",
	},
	department:{
		list_container	:"ul[data-role=listview] li",
		image			:"ul[data-role=listview] li a > div:first-of-type > img",
		list_name		:"div a div:nth-child(2)",
		list_link		:"div a",
		//name			:"#ctl00_PageContent_lblName",
		phone			:"#ctl00_PageContent_lblTel",
		fax				:"#ctl00_PageContent_lblFax",
		address			:"#ctl00_PageContent_lblAddress",
	},
	onScreen_movie:{
		container 		: "div.col-main > div.category-products > ul > li > div > a",
		image			:"div.col-main > div.category-products > ul > li > div > a img",
		name			:"div.product-name span",
		start_time		:"div.movie-release.movie-info div",
		kind			:"div.movie-genre.movie-info div",
		player			:"div.movie-actress.movie-info div",
		director		:"div.movie-director.movie-info div",
		length			:"div.movie-actress.movie-info div",
		language		:"div.movie-language.movie-info div",
		intro			:"dl#collateral-tabs > dd:first-of-type > div > div",
		trailer			:"div#movie-trailer",
		age				:"span[class*=movie-rating-nc]",
	},
	// onScreen_movie:{
	// 	container 		: "#movies_content_2 > ul li a",
	// 	image			:"#movies_content_2 > ul li a > div:first-of-type > img",
	// 	name			:"div:first-child > h2",
	// 	start_time		:"#ctl00_PageContent_lblReleaseDate",
	// 	kind			:"#ctl00_PageContent_lblGenre",
	// 	player			:"#ctl00_PageContent_lblCast",
	// 	director		:"#ctl00_PageContent_lblDirector",
	// 	length			:"#ctl00_PageContent_lblRunningTime",
	// 	intro			:"#ctl00_PageContent_lblDescription",
	// 	trailer			:"#ctl00_PageContent_hplTrailer",
	// },
	commingSoon_movie:{
		container 		: "div.col-main > div.category-products > ul > li > div > a",
		image			:"div.col-main > div.category-products > ul > li > div > a img",
		name			:"div.product-name span",
		start_time		:"div.movie-release.movie-info div",
		kind			:"div.movie-genre.movie-info div",
		player			:"div.movie-actress.movie-info div",
		director		:"div.movie-director.movie-info div",
		length			:"div.movie-actress.movie-info div",
		language		:"div.movie-language.movie-info div",
		intro			:"dl#collateral-tabs > dd:first-of-type > div > div",
		trailer			:"div#movie-trailer",
	},
	promotion_movie:{
		container 		: "div.ss-list li a",
		image			:"div.ss-list li a > div:first-of-type > img",
		//info_container  : "#wrapperDetail div:nth-of-type(2) > table",
		title 			: "#wrapperDetail div:nth-of-type(2) > table tr:nth-of-type(2)",
		content 		: "#wrapperDetail div:nth-of-type(2) > table tr:nth-of-type(3)",
	}
};

module.exports = config;