var config = {
	schedule_link	:"https://www.galaxycine.vn/vi/lich-chieu-dat-ve",
	department_link	:"https://www.galaxycine.vn/vi/rap-gia-ve-lich-chieu-phim",
	onScreen_movie_link	:"https://www.galaxycine.vn/vi/phim/nowshowing",
	commingSoon_movie_link	:"https://www.galaxycine.vn/vi/phim/comingsoon",
	promotion_link	:"https://www.galaxycine.vn/vi/khuyen-mai-su-kien",
	schedule:{
		menu_link 	: "#showTimeMenu a:nth-of-type(2)",
		department 	: "#hCinemas table tr td:first-child div:nth-child(2) div",
		department_param_set:{
			"jp" : "YWpheA==",
			"ja" : "aENpbmVtYXM=",
			"jt" : "Y29sMQ==",
			"je" : "Y2xpY2s="
		},
		movie_param_set:{
			"jp" : "YWpheA==",
			"ja" : "aENpbmVtYXM=",
			"jt" : "Y29sMg==",
			"je" : "Y2xpY2s="
		},
		post_link 			: "https://www.galaxycine.vn/actionServlet",
		department_param 	: "lbCol1",
		movie_param 		: "lbCol2",
	},
	department:{
		container : "div.cinema ul.cinema-items li a",
		param_set:{
			"jp" : "YWpheA==",
			"ja" : "cGFnZS02",
			"jt" : "cGFnZQ==",
			"je" : "Y2luZW1h",
		},
		param		: "id",
		post_link 	: "https://www.galaxycine.vn/actionServlet",
	},
	onScreen_movie	:{
		container		: "#pgMain div:first-of-type div div div a",
		image		: "#pgMain > div:first-of-type > div > div > a >img",
		info_container	: "#pageContent > div:first-of-type > div:first-of-type > div:first-of-type > div:first-of-type > div:first-of-type > div:nth-of-type(2)",
		intro			: "#pageContent > div:first-of-type > div:first-of-type > div:first-of-type > div:first-of-type > div:first-of-type > div:nth-of-type(4)",
		name			:"h2",
		version 		:".btns .caption",
		trailer			:"#btnTrailer",
		start_time		:"div.lbl:nth-of-type(2)",
		kind			:"div.lbl:nth-of-type(3)",
		player			:"div.lbl:nth-of-type(4)",
		director		:"div.lbl:nth-of-type(5)",
		length			:"div.lbl:nth-of-type(6)",
	},
	commingSoon_movie	:{
		container		: "#pgMain div:first-of-type div div div a",
		image			: "#pgMain > div:first-of-type > div > div > a >img",
		info_container	: "#pageContent > div:first-of-type > div:first-of-type > div:first-of-type > div:first-of-type > div:first-of-type > div:nth-of-type(2)",
		intro			: "#pageContent > div:first-of-type > div:first-of-type > div:first-of-type > div:first-of-type > div:first-of-type > div:nth-of-type(4)",
		name			:"h2",
		version 		:".btns .caption",
		trailer			:"#btnTrailer",
		start_time		:"div.lbl:nth-of-type(2)",
		kind			:"div.lbl:nth-of-type(3)",
		player			:"div.lbl:nth-of-type(4)",
		director		:"div.lbl:nth-of-type(5)",
		note			:"div.lbl:nth-of-type(6)",
	},
	promotion:{
		container		:"#root > div",
		image			:"#root > div > a > img",
		link			:"a",
		expired			:"span",
		content			:"#pageContent > div:first-of-type > div:first-of-type > div:first-of-type > div:first-of-type > div:first-of-type > div:nth-of-type(2)",
		title			:"#pageContent > div:first-of-type > div:first-of-type > div:first-of-type > div:first-of-type > div:first-of-type h2",
		param_set:{
			"jp"		:"YWpheA==",
			"ja"		:"cGFnZS0xMQ==",
			"jt"		:"cGdNYWlu",
			"je"		:"cGFnaW5n",
			"pgMain"	:"temp=1",
			"rows"		:8,
		},
		page_param		:"page",
		post_link		:"https://www.galaxycine.vn/actionServlet",
	},
};

module.exports = config;