var config = {
		param		:["__EVENTVALIDATION","__EVENTARGUMENT","__LASTFOCUS","__VIEWSTATE"],
		query_department	:"ddlCinema",
		query_date	:"ddlPlayDate",
		form		:"form1",
		department	:"#ddlCinema > option",
		date			:"#ddlPlayDate > option",
		param_set	:{"__EVENTTARGET":"ddlCinema","btnView":"Xem lịch chiếu"},//"ddlPlayDate":"-1"},
		schedule	:{
			container 	:"div.fancy-c ul li.schedule",
			title		:"div.bottom",
			times		:"div.item div.container div.content font",
		},
		department_parser	:{
			container 	:"#dn_sidebar > div > ul > li",
			image 	:"#dn_primaryc > div:nth-child(2) > div:nth-child(2) > div > img",
			area		:"span > a:first-child",
			link		:"ul > li > a:first-child",
			intro		:"#dn_primaryc > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > span",
			name		:"#dn_primaryc > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > h1"
			
		},
		onScreen_movie	:{
			container		:"#dn_primaryc div:nth-of-type(2) div:nth-of-type(1) ul li div:nth-of-type(2) ul",
			image			:"#dn_primaryc div:nth-of-type(2) div:nth-of-type(1) ul li div:nth-of-type(2) a > img",
			link			:"li:first-child > a",
			name			:"#dn_primaryc > div:nth-of-type(2)> div:first-child > span",
			info_container	:"#dn_primaryc > div:nth-of-type(2) > div:nth-of-type(3) > div:nth-of-type(5) ul",
			start_time		:"li:nth-of-type(1) span:nth-of-type(2)",
			kind			:"li:nth-of-type(2) span:nth-of-type(2)",
			player			:"li:nth-of-type(3) span:nth-of-type(2)",
			director		:"li:nth-of-type(4) span:nth-of-type(2)",
			length			:"li:nth-of-type(5) span:nth-of-type(2)",
			version			:"li:nth-of-type(6) span:nth-of-type(2)",
			intro			:"div.dn_contentmvdt.dn_tabsmvdt1",
			//company			:"li:nth-of-type(7) span:nth-of-type(2)",
			note			:"li:nth-of-type(8) span:nth-of-type(2)",
			trailer			:"#dn_primaryc > div:nth-of-type(2) > div:nth-of-type(5) iframe",
		},
		commingSoon_movie	:{
			container		:"#dn_primaryc div:nth-of-type(2) div:nth-of-type(1) ul li div:nth-of-type(2) ul",
			image			:"#dn_primaryc div:nth-of-type(2) div:nth-of-type(1) ul li div:nth-of-type(2) a > img",
			link			:"li:first-child > a",
			name			:"#dn_primaryc > div:nth-of-type(2)> div:first-child > span",
			info_container	:"#dn_primaryc > div:nth-of-type(2) > div:nth-of-type(3) > div:nth-of-type(5) ul",
			start_time		:"li:nth-of-type(1) span:nth-of-type(2)",
			kind			:"li:nth-of-type(2) span:nth-of-type(2)",
			player			:"li:nth-of-type(3) span:nth-of-type(2)",
			director		:"li:nth-of-type(4) span:nth-of-type(2)",
			length			:"li:nth-of-type(5) span:nth-of-type(2)",
			version			:"li:nth-of-type(6) span:nth-of-type(2)",
			intro			:"div.dn_contentmvdt.dn_tabsmvdt1",
			//company			:"li:nth-of-type(7) span:nth-of-type(2)",
			note			:"li:nth-of-type(8) span:nth-of-type(2)",
			trailer			:"#dn_primaryc > div:nth-of-type(2) > div:nth-of-type(5) iframe",
		},
		promotion:{
			container		:"#dn_primaryc div:nth-of-type(2) div:first-of-type li > div:first-of-type > a",
			next_link		:"#dn_primaryc > div:nth-of-type(2) > div:first-of-type > div:first-of-type > div:nth-of-type(3) > div:nth-of-type(2) span:nth-child(5) a:first-child",
			content			:"#dn_primaryc > div:nth-of-type(2) > div:nth-of-type(3) > div:nth-of-type(5)",
			title			:"#dn_primaryc > div:nth-of-type(2) > div:first-of-type > span",

		},
		schedule_link			:"http://lottecinemavn.com/CMSTemplates/MBMTemplate/FancyboxSchedule.aspx",
		department_link			:"http://lottecinemavn.com/vi-vn/rap-phim/ho-chi-minh/nam-sai-gon.aspx",
		onScreen_movie_link		: "http://lottecinemavn.com/vi-vn/phim-%C4%91ang-chieu.aspx",
		commingSoon_movie_link 	: "http://lottecinemavn.com/vi-vn/phim-sap-chieu.aspx",
		promotion_link			:"http://lottecinemavn.com/vi-vn/su-kien.aspx?page=",
}

module.exports = config;
